################################### Default Configuration ############################
baseurl = "/"
languageCode = "en"
title = "MACBING 맥빙"
theme = "vex-hugo"

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
[[params.plugins.css]]
URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
URL = "css/bootstrap.min.css" # 구조 
[[params.plugins.css]]
URL = "css/themefisher-fonts.css" # 돋보기 
[[params.plugins.css]]
URL = "css/owl.carousel.css" # gallery
[[params.plugins.css]]
URL = "css/magnific-popup.css"
[[params.plugins.css]]
URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery-2.1.1.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/owl.carousel.min.js"
[[params.plugins.js]]
URL = "js/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"


###################################### Navigation ######################################

[[menu.main]]
name = "제품 사양"
URL = "feature"
weight = 2

[[menu.main]]
name = "갤러리"
URL = "gallery"
weight = 3

########################### Default parameters ##########################
[params]
logo = ""
home = "홈"
# Meta data
description = ""
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "" # Your ID
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
# copyright
copyright = "주식회사 맥빙 | 경기도 고양시 일산동구 정발산로 24 웨스턴타워 4동410호 | Tel: 031-901-7260"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format
